
use customer_trend
SELECT * from customer
limit 20
/* what is total revenue generated by male and female customers */
SELECT gender, SUM(`purchase_amount_(usd)`) AS revenue
FROM customer
GROUP BY gender;

/* which customers used a discount but still spent more than the average purchase amount*/
SELECT customer_id, `purchase_amount_(usd)`
FROM customer
WHERE discount_applied = 'Yes'
AND `purchase_amount_(usd)` >= (
    SELECT AVG(`purchase_amount_(usd)`)
    FROM customer
);

/* which are the top 5 products with highest average review  review rating*/
select item_purchased, round(avg(review_rating),2)as average_product_rating  from customer
group by item_purchased
order by avg(review_rating) desc
limit 5
/*compare the average purchase amounts between standard and Express shipping*/
SELECT shipping_type,
       round(AVG(`purchase_amount_(usd)`),2)AS average_amount
FROM customer
where shipping_type in ("Express","Standard")
GROUP BY shipping_type;

/*Do subscribed customers spend more ? compare average spend and total revenue between subscribers and non- subscribers*/
select subscription_status, count(customer_id),avg(`purchase_amount_(usd)`) as average_spend , sum(`purchase_amount_(usd)`) as total_revenue
 from customer
group by(subscription_status)
order by total_revenue desc 

/* which 5 products have the highest percentage of purchases with discounts applieed*/
select item_purchased , (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
       / COUNT(*)) * 100 AS percentage 
from customer
group by (item_purchased)
order by percentage desc limit 5

/*segment customers into now , returning, and Loyal based on their total number of previous purchases and show the count of each segment */
select case
when previous_purchases =1 then "new"
when previous_purchases between 1 and 5 then "returning"
else "loyal"
end
as customer_segment ,count(customer_id) as total_customer
from customer
group by (customer_segment)

/* what are the top 3 most purchase product in each category*/
SELECT *
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
) t
WHERE item_rank <= 3;

/*are customers who are repeat buyers(more than  5 previous purchases) also likely to subscribe*/
select subscription_status, count(*) as total_repeat_customer 
from customer
where previous_purchases>5
group by subscription_status

/*what is the revenue contribution of each age group*/
select case when age  between 10 and 35 then "young adults"
			when age between 35 and 45 then "adult"
            when age between 45 and 55 then "Middle_aged"
            else "senior" end as age_group , sum(`purchase_amount_(usd)`) as total_revenue
from customer
group by age_group
 order by total_revenue desc
